Invoke puppet with apply command. Remove debug option

diff --git a/files/puppet/launch-puppet b/files/puppet/launch-puppet
--- a/files/puppet/launch-puppet
+++ b/files/puppet/launch-puppet
@@ -16,7 +16,7 @@ if [ "$1" = "boot" ]; then
 
         stored_config="/boot/config.pp.`facter macaddress`"
         [ ! -f $stored_config ] && stored_config="/boot/config.pp"
-        
+
         cp $stored_config "/var/etc/puppet/manifests/config.pp"
         chown www-data "/var/etc/puppet/manifests/config.pp"
     fi
@@ -25,7 +25,7 @@ if [ "$1" = "boot" ]; then
     /usr/local/bin/box config migrate
 fi
 
-/usr/bin/puppet --debug $options /etc/puppet/manifests/site.pp
+/usr/bin/puppet apply $options /etc/puppet/manifests/site.pp
 puppet_error_level=$?
 
 if [ "$1" = "boot" ]; then
@@ -46,7 +46,9 @@ if [ "$1" = "boot" ]; then
             exit 1
         fi
     fi
+else
+    if [ $puppet_error_level != 0 ]; then
+        echo "Errors during puppet configuration, check syslog"
+        # exit $puppet_error_level
+    fi
 fi
-
-
-
